version: '3'
services:
  estacionamento:
    build:
      context: .
      dockerfile: ./dockers/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source:/source
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
