# Generated by Django 3.0.2 on 2020-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7)),
                ('reservation_number', models.CharField(max_length=7)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
            ],
        ),
    ]
