# Generated by Django 3.0.2 on 2020-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='arrival',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='departure',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='reservation_number',
            field=models.IntegerField(auto_created=True, blank=True, serialize=False, verbose_name='Reserva'),
        ),
    ]
