# Generated by Django 3.0.2 on 2020-02-02 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_auto_20200202_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='arrival',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='plate',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z][a-zA-Z]\\-[0-9][0-9][0-9][0-9]$', 'Insira uma placa no formato AAA-9999')], verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='reservation',
            field=models.CharField(max_length=9, verbose_name='Número da Reserva'),
        ),
    ]
